#!/usr/bin/env python3
"""
Convert a vendored 3rd_training_lua ROM box dump into PyKuma hitbox YAML.

NO INVENTED DATA. This tool only emits geometry and timing that exist in the
vendored ROM dump, plus combat (damage/stun/advantage) values copied verbatim
from the community frame-data tier. It never fabricates boxes or numbers.

Three provenance tiers are produced and tagged in the output:
  - verified : box geometry + frame timing, dumped from the SF3:3S ROM.
  - inferred : the assignment of a ROM pointer to a game CharacterState
               (the move's *name*). ROM-verified geometry, guessed identity.
  - community: damage / stun / frame advantage, from Baston ESN3S frame data
               plus existing gameplay tuning. NOT ROM-verified.

Source convention (input JSON):
  Each box = {type, left, bottom, width, height}. `left`/`bottom` are the box's
  lower-left EDGES; X spans [left, left+width], Y-above-ground spans
  [bottom, bottom+height]. Forward is -x (attack boxes sit at negative x).

PyKuma convention (output):
  offset_y = TOP edge, negative = up from ground (feet at y=0).
  Attack offset_x = LEFT edge, forward-positive.
  Hurt/push/throw offset_x = CENTER, forward-positive.

Usage:
  python tools/framedata/convert_3rd_training.py data/sources/gouki_framedata.json \
      --name akuma \
      --names data/characters/akuma/move_names.json \
      --combat data/characters/akuma/sf3_authentic_frame_data.yaml \
      --out data/characters/akuma/hitboxes.yaml
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

# 3rd_training_lua provenance (matches data/sources/SOURCE.txt).
REPO = "https://github.com/Grouflon/3rd_training_lua"
COMMIT = "73ec4c062108fd3494c4fae6b81a61f9cf518b81"
ROM_REVISION = "sfiii3nr1"
SCALE_REFERENCE_HEIGHT = 107  # native character height in px; NO scale factor applied

# Box types that use a CENTER-based offset_x in PyKuma.
_CENTERED_TYPES = {"vulnerability", "push", "throwable"}

# Combat values carried from the previous hand-tuned akuma_hitboxes.py literals.
# Damage/stun/advantage come from the --combat yaml; hit_type/hit_effect and the
# hitstun/blockstun are preserved here to keep existing gameplay behavior.
# Keyed by CharacterState name -> (yaml_key, hit_type, hit_effect, hitstun, blockstun)
COMBAT_MAP = {
    "LIGHT_PUNCH":         ("standing_light_punch",   "HIGH", "NORMAL",    12, 10),
    "MEDIUM_PUNCH":        ("standing_medium_punch",  "MID",  "NORMAL",    15, 12),
    "HEAVY_PUNCH":         ("standing_heavy_punch",   "HIGH", "JUGGLE",    18, 14),
    "LIGHT_KICK":          ("standing_light_kick",    "HIGH", "NORMAL",    13, 11),
    "MEDIUM_KICK":         ("standing_medium_kick",   "HIGH", "NORMAL",    16, 13),
    "HEAVY_KICK":          ("standing_heavy_kick",    "HIGH", "NORMAL",    20, 15),
    "CROUCH_LIGHT_PUNCH":  ("crouching_light_punch",  "MID",  "NORMAL",    12, 10),
    "CROUCH_LIGHT_KICK":   ("crouching_light_kick",   "LOW",  "NORMAL",    13, 11),
    "CROUCH_MEDIUM_KICK":  ("crouching_medium_kick",  "LOW",  "NORMAL",    16, 13),
    "CROUCH_HEAVY_KICK":   ("crouching_heavy_kick",   "LOW",  "KNOCKDOWN", 20, 15),
    "JUMP_LIGHT_PUNCH":    ("jump_light_punch",       "HIGH", "NORMAL",    12, 10),
    "JUMP_MEDIUM_PUNCH":   ("jump_medium_punch",      "HIGH", "NORMAL",    15, 13),
    "JUMP_HEAVY_PUNCH":    ("jump_heavy_punch",       "HIGH", "NORMAL",    18, 14),
    "JUMP_LIGHT_KICK":     ("jump_light_kick",        "HIGH", "NORMAL",    13, 11),
    "JUMP_MEDIUM_KICK":    ("jump_medium_kick",       "HIGH", "NORMAL",    16, 13),
    "JUMP_HEAVY_KICK":     ("jump_heavy_kick",        "HIGH", "NORMAL",    20, 15),
}

COMBAT_SOURCE = ("Baston ESN3S frame data + existing gameplay tuning; "
                 "NOT ROM-verified")

# Top-level non-move string keys in the source JSON.
_SKIP_KEYS = {"idle", "wakeups", "wakeup_to_idle"}

BANNER = (
    "# NO INVENTED DATA. Generated by tools/framedata/convert_3rd_training.py.\n"
    "# Provenance tiers:\n"
    "#   verified : box geometry + frame timing, dumped from the SF3:3S ROM "
    "(3rd_training_lua).\n"
    "# name_status on each move:\n"
    "#   metadata : ROM-pointer -> move name taken verbatim from framedata_meta.lua "
    "(authoritative).\n"
    "#   inferred : ROM-pointer -> move name guessed from timing/geometry "
    "(geometry ROM-verified, NAME is a guess).\n"
    "#   (unnamed): geometry-only ROM animation, not yet mapped to a move.\n"
    "#   community: damage / stun / frame advantage, from Baston ESN3S + "
    "gameplay tuning; NOT ROM-verified.\n"
    "# Do not hand-edit; regenerate from the vendored source instead.\n"
)


def convert_box(box, *, centered: bool):
    """Convert one source box dict to PyKuma offsets.

    offset_y = -(bottom + height)              (TOP edge, negative = up)
    attack (not centered): offset_x = -left - width        (LEFT edge, forward+)
    centered (hurt/push/throw): offset_x = -(left + width/2) (CENTER, forward+)
    No scale factor is applied (native ~107px).
    """
    offset_y = -(box["bottom"] + box["height"])
    if centered:
        offset_x = -(box["left"] + box["width"] / 2)
    else:
        offset_x = -box["left"] - box["width"]
    return {
        "offset_x": float(offset_x),
        "offset_y": float(offset_y),
        "width": float(box["width"]),
        "height": float(box["height"]),
    }


def _active_indices(frames):
    """0-based indices of frames whose boxes include an attack box."""
    return [i for i, fr in enumerate(frames)
            if any(b["type"] == "attack" for b in fr.get("boxes", []))]


def compute_timing(frames):
    """startup/active/recovery/total from a move's frames list."""
    active = _active_indices(frames)
    if not active:
        return None
    startup = active[0]
    active_count = len(active)
    recovery = (len(frames) - 1) - active[-1]
    return {
        "startup": startup,
        "active": active_count,
        "recovery": recovery,
        "total": len(frames),
    }


def extract_base_boxes(idle_entry):
    """Pull pushbox, throwbox, and base_hurtbox list from idle frame 0."""
    boxes = idle_entry["frames"][0]["boxes"]
    pushbox = None
    throwbox = None
    base_hurtbox = []
    for b in boxes:
        if b["type"] == "push":
            pushbox = convert_box(b, centered=True)
        elif b["type"] == "throwable":
            throwbox = convert_box(b, centered=True)
        elif b["type"] == "vulnerability":
            base_hurtbox.append(convert_box(b, centered=True))
    return pushbox, throwbox, base_hurtbox


def _approx(a, b, tol=0.6):
    return abs(a - b) <= tol


def self_check(pushbox, throwbox, base_hurtbox):
    """Assert the well-known idle base-box values (sanity guard)."""
    assert pushbox and _approx(pushbox["offset_x"], 0) and _approx(pushbox["offset_y"], -84) \
        and _approx(pushbox["width"], 50) and _approx(pushbox["height"], 84), \
        f"pushbox self-check failed: {pushbox}"
    assert throwbox and _approx(throwbox["offset_x"], 0) and _approx(throwbox["offset_y"], -16) \
        and _approx(throwbox["width"], 50) and _approx(throwbox["height"], 16), \
        f"throwbox self-check failed: {throwbox}"
    assert len(base_hurtbox) == 4, f"expected 4 base hurtboxes, got {len(base_hurtbox)}"
    head = next((b for b in base_hurtbox
                 if _approx(b["offset_x"], 3) and _approx(b["offset_y"], -101)
                 and _approx(b["width"], 22) and _approx(b["height"], 20)), None)
    legs = next((b for b in base_hurtbox
                 if _approx(b["offset_x"], -0.5) and _approx(b["offset_y"], -36)
                 and _approx(b["width"], 65) and _approx(b["height"], 36)), None)
    assert head is not None, f"base_hurtbox missing head box; got {base_hurtbox}"
    assert legs is not None, f"base_hurtbox missing legs box; got {base_hurtbox}"


def load_names(names_path):
    """Return {rom_id: {state, confidence, rationale}} from move_names.json."""
    if not names_path or not Path(names_path).exists():
        return {}
    data = json.loads(Path(names_path).read_text())
    out = {}
    for state, info in data.items():
        if state.startswith("_"):
            continue
        out[info["rom_id"]] = {
            "state": state,
            "name_source": info.get("name_source", "inferred"),
            "confidence": info.get("confidence"),
            "rationale": info.get("rationale", ""),
        }
    return out


def load_combat(combat_path):
    """Return {state_name: combat_dict} from the community frame-data yaml."""
    if not combat_path or not Path(combat_path).exists():
        return {}
    raw = yaml.safe_load(Path(combat_path).read_text())
    normals = (raw or {}).get("normal_attacks", {})
    out = {}
    for state, (yaml_key, hit_type, hit_effect, hitstun, blockstun) in COMBAT_MAP.items():
        entry = normals.get(yaml_key)
        if not entry:
            continue
        out[state] = {
            "damage": int(entry.get("damage", 0)),
            "stun": int(entry.get("stun", 0)),
            "on_hit": int(entry.get("hit_advantage", 0)),
            "on_block": int(entry.get("block_advantage", 0)),
            "hitstun": int(hitstun),
            "blockstun": int(blockstun),
            "hit_type": hit_type,
            "hit_effect": hit_effect,
            "status": "community",
            "source": COMBAT_SOURCE,
        }
    return out


def build_move(rom_id, entry, names, combat):
    """Build one move record dict, or None if it has no attack frames."""
    frames = entry.get("frames", [])
    timing = compute_timing(frames)
    if timing is None:
        return None

    active = _active_indices(frames)
    name_info = names.get(rom_id)

    out_frames = []
    for idx in active:
        attack_boxes = []
        for b in frames[idx].get("boxes", []):
            if b["type"] != "attack":
                continue
            conv = convert_box(b, centered=False)
            conv["status"] = "verified"
            conv["rom_id"] = rom_id
            attack_boxes.append(conv)
        out_frames.append({"frame": idx + 1, "attack": attack_boxes})

    record = {
        "rom_id": rom_id,
        "timing": timing,
        "source": {
            "repo": REPO,
            "commit": COMMIT,
            "rom_id": rom_id,
            "status": "verified",
        },
        "frames": out_frames,
    }

    if name_info:
        record["state"] = name_info["state"]
        # metadata = name taken verbatim from framedata_meta.lua (authoritative);
        # inferred = name guessed from timing/geometry.
        src = name_info.get("name_source", "inferred")
        record["name_status"] = "metadata" if src == "metadata" else "inferred"
        if name_info.get("confidence"):
            record["confidence"] = name_info["confidence"]
        combat_block = combat.get(name_info["state"])
        if combat_block:
            record["combat"] = combat_block

    return record


def build_document(source_json, name, names, combat):
    data = json.loads(Path(source_json).read_text())

    pushbox, throwbox, base_hurtbox = extract_base_boxes(data["idle"])
    self_check(pushbox, throwbox, base_hurtbox)

    def tag_base(box):
        box = dict(box)
        box["status"] = "verified"
        box["rom_id"] = "idle"
        return box

    moves = {}
    for rom_id, entry in data.items():
        if rom_id in _SKIP_KEYS:
            continue
        if not isinstance(entry, dict) or "frames" not in entry:
            continue
        rec = build_move(rom_id, entry, names, combat)
        if rec is not None:
            moves[rom_id] = rec

    doc = {
        "meta": {
            "character": name,
            "coordinate_space": "pykuma",
            "scale_reference_height": SCALE_REFERENCE_HEIGHT,
            "source": {
                "repo": REPO,
                "commit": COMMIT,
                "rom_revision": ROM_REVISION,
                "file": "data/sources/gouki_framedata.json",
            },
            "notes": (
                "NO INVENTED DATA. geometry+timing = ROM verified "
                "(3rd_training_lua); move names = metadata (from framedata_meta.lua) "
                "where annotated, else inferred (a guess) or unnamed; combat values "
                "(damage/stun/advantage) = community (Baston ESN3S + tuning, NOT "
                "ROM-verified)."
            ),
        },
        "base_hurtbox": [tag_base(b) for b in base_hurtbox],
        "pushbox": tag_base(pushbox),
        "throwbox": tag_base(throwbox),
        "moves": moves,
    }
    return doc


def dump_yaml(doc, out_path):
    """Write YAML deterministically: meta/base first, moves sorted."""
    moves = doc.pop("moves")
    sorted_moves = {k: moves[k] for k in sorted(moves)}

    with open(out_path, "w") as f:
        f.write(BANNER)
        # Emit the top section in declared order (meta/base/push/throw).
        yaml.safe_dump(doc, f, default_flow_style=False, sort_keys=False)
        f.write("moves:\n")
        for rom_id, rec in sorted_moves.items():
            block = yaml.safe_dump({rom_id: rec}, default_flow_style=False,
                                   sort_keys=False)
            for line in block.splitlines():
                f.write("  " + line + "\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("source", help="path to vendored gouki_framedata.json")
    parser.add_argument("--name", default="akuma", help="character name")
    parser.add_argument("--names", default=None,
                        help="move_names.json (default: data/characters/<name>/move_names.json)")
    parser.add_argument("--combat", default=None,
                        help="community frame-data yaml (default: "
                             "data/characters/<name>/sf3_authentic_frame_data.yaml)")
    parser.add_argument("--out", default=None,
                        help="output yaml (default: data/characters/<name>/hitboxes.yaml)")
    args = parser.parse_args(argv)

    char_dir = Path("data/characters") / args.name
    names_path = args.names or (char_dir / "move_names.json")
    combat_path = args.combat or (char_dir / "sf3_authentic_frame_data.yaml")
    out_path = args.out or (char_dir / "hitboxes.yaml")

    names = load_names(names_path)
    combat = load_combat(combat_path)

    doc = build_document(args.source, args.name, names, combat)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    n_moves = len(doc["moves"])
    dump_yaml(doc, out_path)

    print(f"Wrote {out_path} ({n_moves} moves)")
    print(f"base_hurtbox boxes: {len(doc['base_hurtbox'])}")
    print(f"pushbox: {doc['pushbox']}")
    print(f"throwbox: {doc['throwbox']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
