"""
Akuma hitbox / frame-data shim (delegates to the ROM-verified repository).

NO INVENTED DATA. This module no longer contains hand-eyeballed hitbox numbers.
It is a thin compatibility layer over ``hitbox_repository``, which loads
``data/characters/akuma/hitboxes.yaml`` (generated by
``tools/framedata/convert_3rd_training.py``).

Provenance of the values surfaced here:
  - geometry + frame timing : ROM-verified (SF3:3S via 3rd_training_lua).
  - move names (state->move) : INFERRED (the ROM-pointer assignment is a guess).
  - damage / stun / advantage: community (Baston ESN3S + tuning, NOT ROM-verified).

The public API (dataclasses + the three ``get_*`` functions) is preserved
verbatim because the collision adapter and the test-suite depend on it.

Position reference (unchanged):
  - X offset: positive = forward, negative = backward.
  - Y offset: negative = up from ground, positive = down.
"""

from dataclasses import dataclass
from typing import List, Tuple

from street_fighter_3rd.data.enums import HitType, CharacterState, HitEffect
from street_fighter_3rd.data.hitbox_repository import HitboxRepository, MoveRecord, SourcedBox

_HIT_TYPE_BY_NAME = {
    "HIGH": HitType.HIGH,
    "MID": HitType.MID,
    "LOW": HitType.LOW,
    "OVERHEAD": HitType.OVERHEAD,
}
_HIT_EFFECT_BY_NAME = {
    "NORMAL": HitEffect.NORMAL,
    "KNOCKDOWN": HitEffect.KNOCKDOWN,
    "JUGGLE": HitEffect.JUGGLE,
}

# States that should use the crouch-scaled hurtbox stack.
_CROUCH_STATES = {CharacterState.CROUCHING, CharacterState.CROUCH_HEAVY_KICK}


@dataclass
class HitboxFrame:
    """Defines a hitbox for a specific frame or frame range"""
    offset_x: int  # X offset from character center (+ = forward)
    offset_y: int  # Y offset from ground (- = up, + = down)
    width: int
    height: int
    damage: int
    hitstun: int  # Frames of hitstun on hit
    blockstun: int  # Frames of blockstun on block
    hit_type: HitType = HitType.MID


@dataclass
class HurtboxFrame:
    """Defines character's hurtbox (vulnerable area)"""
    offset_x: int
    offset_y: int
    width: int
    height: int


@dataclass
class MoveFrameData:
    """Complete frame data for a move"""
    name: str
    state: CharacterState
    startup: int  # Frames before active
    active: List[int]  # List of active frame numbers (1-indexed)
    recovery: int  # Frames after active
    on_hit: int  # Frame advantage on hit
    on_block: int  # Frame advantage on block
    hitboxes: List[Tuple[List[int], HitboxFrame]]  # (active_frames, hitbox)
    hurtboxes: List[HurtboxFrame]  # Character's vulnerable areas
    hit_effect: HitEffect = HitEffect.NORMAL  # reaction this move causes on hit
    # ROM total move duration. NOT always startup+len(active)+recovery: a
    # multi-hit move has a GAP between active windows (s.HK: active 6-8 and
    # 16-20 inside a 39-frame total). This is the duration the engine runs.
    total: int = 0


def _repo() -> HitboxRepository:
    return HitboxRepository.instance()


def _box_key(box: SourcedBox) -> Tuple[int, int, int, int]:
    return (round(box.offset_x), round(box.offset_y),
            round(box.width), round(box.height))


def _active_windows(active: List[int]) -> List[List[int]]:
    """Split the 1-indexed active frame list into contiguous windows.
    A single-hit move has one window; s.HK has two ([6,7,8] and [16..20])."""
    windows: List[List[int]] = []
    for f in active:
        if windows and f == windows[-1][-1] + 1:
            windows[-1].append(f)
        else:
            windows.append([f])
    return windows


_STUN_CACHE: dict = {}


def _calibrated_stun(move: MoveRecord) -> Tuple[int, int] | None:
    """(hitstun, blockstun) derived FROM the community advantage numbers.

    The combat tier's stored hitstun/blockstun are estimates and are NOT
    mutually consistent with the ROM timing + the community on_hit/on_block
    (e.g. s.MK: hitstun 16 with total 23 and hit on frame 5 can only ever
    yield -3 on hit, but the community advantage is +1). Advantage is what the
    community actually documents, so it is the source of truth; hitstun and
    blockstun are back-solved from it against the ROM-verified timeline:

        advantage = (hit_frame + stun) - (total + 1)
        => stun    = advantage + (total + 1) - hit_frame

    with hit_frame = the first frame of the LAST active window (advantage is
    quoted for a normal point-blank connect: earliest frame of the final hit;
    earlier hits of a multi-hit move keep the defender stunned into the next
    window). Grounded normals only: air normals resolve through the airborne
    hitstun/knockdown model, where quoted advantage does not apply.
    Returns None (keep the stored estimates) when the record lacks the data.
    """
    key = move.state or move.rom_id
    if key in _STUN_CACHE:
        return _STUN_CACHE[key]
    result = None
    combat = move.combat
    state_name = move.state or ""
    if (combat is not None
            and combat.on_hit is not None and combat.on_block is not None
            and not state_name.startswith("JUMP_")):
        total = int(move.timing.get("total") or 0)
        active = move.active_frames()
        if total and active:
            ref = _active_windows(list(active))[-1][0]
            hitstun = int(combat.on_hit) + (total + 1) - ref
            blockstun = int(combat.on_block) + (total + 1) - ref
            if hitstun > 0 and blockstun > 0:
                result = (hitstun, blockstun)
    _STUN_CACHE[key] = result
    return result


def _hitbox_from_box(box: SourcedBox, move: MoveRecord) -> HitboxFrame:
    combat = move.combat
    damage = combat.damage if combat else 0
    calibrated = _calibrated_stun(move)
    if calibrated is not None:
        hitstun, blockstun = calibrated
    else:
        hitstun = combat.hitstun if combat else 0
        blockstun = combat.blockstun if combat else 0
    hit_type = _HIT_TYPE_BY_NAME.get(combat.hit_type if combat else "MID", HitType.MID)
    return HitboxFrame(
        offset_x=int(round(box.offset_x)),
        offset_y=int(round(box.offset_y)),
        width=int(round(box.width)),
        height=int(round(box.height)),
        damage=int(damage),
        hitstun=int(hitstun),
        blockstun=int(blockstun),
        hit_type=hit_type,
    )


def _build_move_frame_data(move: MoveRecord) -> MoveFrameData:
    """Compose a MoveFrameData from a repository MoveRecord."""
    active = move.active_frames()

    # Group identical attack boxes across active frames so the shim emits one
    # (active_frames, hitbox) tuple per distinct box (matches the old shape).
    box_to_frames: dict = {}
    box_to_box: dict = {}
    for frame_no in active:
        for box in move.attack_boxes_for_frame(frame_no):
            key = _box_key(box)
            box_to_frames.setdefault(key, []).append(frame_no)
            box_to_box.setdefault(key, box)

    hitboxes: List[Tuple[List[int], HitboxFrame]] = []
    for key, frames in box_to_frames.items():
        hitboxes.append((frames, _hitbox_from_box(box_to_box[key], move)))

    combat = move.combat
    on_hit = combat.on_hit if combat else 0
    on_block = combat.on_block if combat else 0
    hit_effect = _HIT_EFFECT_BY_NAME.get(combat.hit_effect if combat else "NORMAL",
                                         HitEffect.NORMAL)

    state = getattr(CharacterState, move.state) if move.state else None
    hurtboxes = _compose_hurtboxes(state) if state else []

    return MoveFrameData(
        name=move.state or move.rom_id,
        state=state,
        startup=int(move.timing.get("startup", 0)),
        active=list(active),
        recovery=int(move.timing.get("recovery", 0)),
        on_hit=int(on_hit),
        on_block=int(on_block),
        hitboxes=hitboxes,
        hurtboxes=hurtboxes,
        hit_effect=hit_effect,
        total=int(move.timing.get("total")
                  or (int(move.timing.get("startup", 0)) + len(active)
                      + int(move.timing.get("recovery", 0)))),
    )


def _compose_hurtboxes(state: CharacterState, frame_number: int = 0) -> List[HurtboxFrame]:
    """Base (or crouch-scaled) hurtbox stack, plus per-move vulnerability
    extensions for the given 1-indexed active frame (if any)."""
    repo = _repo()
    if state in _CROUCH_STATES:
        boxes = repo.get_crouch_hurtboxes()
    else:
        boxes = repo.get_base_hurtboxes()
    # Layer the move's per-frame vulnerability boxes (extended limb) on top.
    if frame_number > 0:
        boxes = boxes + repo.get_vulnerability_boxes(state.name, frame_number)
    return [
        HurtboxFrame(
            offset_x=int(round(b.offset_x)),
            offset_y=int(round(b.offset_y)),
            width=int(round(b.width)),
            height=int(round(b.height)),
        )
        for b in boxes
    ]


def get_akuma_hitboxes(state: CharacterState, frame_number: int) -> List[HitboxFrame]:
    """Active attack hitboxes for Akuma's state on a given 1-indexed frame."""
    move = _repo().get_move_by_state(state.name)
    if not move:
        return []
    boxes = move.attack_boxes_for_frame(frame_number)
    return [_hitbox_from_box(b, move) for b in boxes]


def get_akuma_hurtboxes(state: CharacterState, frame_number: int = 0) -> List[HurtboxFrame]:
    """Hurtboxes for Akuma's state: base stack + per-move vulnerability boxes for
    the given 1-indexed active frame (frame_number=0 -> base only)."""
    return _compose_hurtboxes(state, frame_number)


def get_move_frame_data(state: CharacterState) -> MoveFrameData | None:
    """Complete frame data for a move, or None if the state is unmapped."""
    if state is None:
        return None
    move = _repo().get_move_by_state(state.name)
    if not move:
        return None
    return _build_move_frame_data(move)
