"""
ROM-accurate hitbox repository with enforced data provenance.

NO INVENTED DATA. This module is the single source of truth for Akuma's box
geometry. It loads `data/characters/akuma/hitboxes.yaml` (generated by
`tools/framedata/convert_3rd_training.py`) and refuses to load any box that is
not tagged with a provenance status. Tiers:

  - verified : box geometry + frame timing, dumped from the SF3:3S ROM.
  - baston   : geometry cross-matched pixel/sequence-exact to a unique ROM
               pointer against Baston ESN3S (e.g. per-move vulnerability boxes
               that the ROM dump omits); authoritative, pending ROM extraction.
  - inferred : the ROM-pointer -> CharacterState (move name) assignment.
  - community: damage / stun / frame advantage (Baston ESN3S + tuning).

THE INVARIANT (enforced by Pydantic below): a `verified` box/source with no
provenance (empty repo or rom_id) fails to load. On a missing yaml or missing
entry the repository logs once and returns empty -- it NEVER fabricates boxes.
"""

from pathlib import Path
from typing import Dict, Iterable, List, Optional

import logging
import yaml
from pydantic import BaseModel, Field, model_validator

from street_fighter_3rd.data.character_dimensions import get_default_hurtbox_for_character
from street_fighter_3rd.util.logging_config import get_logger, log_once

log = get_logger(__name__)

# Resolve relative to repo root: src/street_fighter_3rd/data/<file> -> repo root.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_HITBOX_YAML = _REPO_ROOT / "data" / "characters" / "akuma" / "hitboxes.yaml"

_VALID_STATUSES = {"verified", "baston", "inferred", "community", "pending"}
_VARIANT_ORDER = ("light", "medium", "heavy", "air_light", "air_medium", "air_heavy")


class Provenance(BaseModel):
    """Where a box / move came from. ``verified`` requires real provenance."""

    status: str
    repo: str = ""
    commit: str = ""
    rom_id: str = ""
    source: str = ""

    @model_validator(mode="after")
    def _check_verified_has_provenance(self):
        if self.status not in _VALID_STATUSES:
            raise ValueError(f"unknown provenance status: {self.status!r}")
        if self.status == "verified":
            if not self.repo or not self.rom_id:
                raise ValueError(
                    "verified provenance requires non-empty repo and rom_id "
                    f"(got repo={self.repo!r}, rom_id={self.rom_id!r})"
                )
        return self


class SourcedBox(BaseModel):
    """A box that cannot exist without a provenance status."""

    offset_x: float
    offset_y: float
    width: float = Field(gt=0)
    height: float = Field(gt=0)
    status: str
    rom_id: str = ""

    @model_validator(mode="after")
    def _require_status(self):
        if not self.status:
            raise ValueError("SourcedBox requires a non-empty provenance status")
        if self.status not in _VALID_STATUSES:
            raise ValueError(f"unknown box status: {self.status!r}")
        return self


class CombatData(BaseModel):
    """Community-tier gameplay values (damage/stun/advantage)."""

    damage: int = 0
    stun: int = 0
    on_hit: int = 0
    on_block: int = 0
    hitstun: int = 0
    blockstun: int = 0
    hit_type: str = "MID"
    hit_effect: str = "NORMAL"
    status: str = "community"
    source: str = ""
    # Community full-move length. Meaningful for `timing_scope == "segment"`
    # records, whose ROM script covers only part of the move.
    total: Optional[int] = None
    # For multi-hit specials the community damage is the move total; `damage`
    # is the per-hit split and this keeps the original figure.
    damage_total: Optional[int] = None


class MoveRecord(BaseModel):
    """One ROM move entry plus optional inferred name + community combat."""

    rom_id: str
    timing: Dict[str, int]
    source: Provenance
    frames: List[Dict] = Field(default_factory=list)
    state: Optional[str] = None
    # Strength variant for move families that share one CharacterState
    # (GOSHORYUKEN light/medium/heavy, TATSUMAKI light/.../air_heavy).
    variant: Optional[str] = None
    name_status: Optional[str] = None
    confidence: Optional[str] = None
    combat: Optional[CombatData] = None
    # ROM hit registrations as 1-indexed [start, end] windows (the dump's
    # `hit_frames`). Distinct hits of a multi-hit move; may be finer than the
    # attack-box runs (HP Goshoryuken: boxes 2-24 but hits 2, 4, 6-23).
    hit_windows: List[List[int]] = Field(default_factory=list)
    # ROM per-frame [dx, dy] in PyKuma units (forward-positive, y grows DOWN),
    # one entry per script frame; [] when the script never moves the fighter.
    movement: List[List[int]] = Field(default_factory=list)
    # "full": the script is the whole move. "segment": the script is only the
    # rise/spin part (fall + landing are separate scripts the dump does not
    # chain) -- timing.total/recovery are NOT the move's duration.
    timing_scope: str = "full"
    # ROM-exact combat tier captured live from the game (ingest.py combat):
    # {"status": "verified", "damage_total", "hits": [{"window", "damage",
    # "stun", "hitstop", "hitstun", "blockstun", "chip", ...}]}. When present
    # it outranks `combat` (community) for damage/hitstun/blockstun.
    rom_combat: Optional[Dict] = None

    def rom_hit(self, window_index: int) -> Optional[Dict]:
        """Captured values for a hit window (falls back to the last captured
        window for a multi-hit move the capture didn't fully cover)."""
        if not self.rom_combat or not self.rom_combat.get("hits"):
            return None
        hits = self.rom_combat["hits"]
        for h in hits:
            if h.get("window") == window_index:
                return h
        return hits[-1]

    def movement_for_frame(self, frame_1indexed: int):
        """(dx, dy) for a script frame, or None past the end of the table."""
        if 1 <= frame_1indexed <= len(self.movement):
            dx, dy = self.movement[frame_1indexed - 1]
            return int(dx), int(dy)
        return None

    def hit_windows_or_derived(self) -> List[List[int]]:
        """ROM hit windows, else contiguous runs of attack-box frames."""
        if self.hit_windows:
            return [[int(a), int(b)] for a, b in self.hit_windows]
        wins: List[List[int]] = []
        for f in self.active_frames():
            if wins and f == wins[-1][1] + 1:
                wins[-1][1] = f
            else:
                wins.append([f, f])
        return wins

    def attack_boxes_for_frame(self, frame_1indexed: int) -> List[SourcedBox]:
        boxes: List[SourcedBox] = []
        for fr in self.frames:
            if fr.get("frame") == frame_1indexed:
                for raw in fr.get("attack", []):
                    boxes.append(SourcedBox(**raw))
        return boxes

    def vulnerability_boxes_for_frame(self, frame_1indexed: int) -> List[SourcedBox]:
        """Per-move vulnerability hurtbox extensions for a frame (centered)."""
        boxes: List[SourcedBox] = []
        for fr in self.frames:
            if fr.get("frame") == frame_1indexed:
                for raw in fr.get("vulnerability", []):
                    boxes.append(SourcedBox(**raw))
        return boxes

    def active_frames(self) -> List[int]:
        return [fr["frame"] for fr in self.frames if fr.get("attack")]


class HitboxRepository:
    """Lazy singleton loader for the ROM-verified hitbox YAML."""

    _instance: Optional["HitboxRepository"] = None

    def __init__(self, yaml_path: Optional[Path] = None):
        self._yaml_path = Path(yaml_path) if yaml_path else _HITBOX_YAML
        self._loaded = False
        self._base_hurtbox: List[SourcedBox] = []
        self._pushbox: Optional[SourcedBox] = None
        self._throwbox: Optional[SourcedBox] = None
        self._moves: Dict[str, MoveRecord] = {}
        self._meta: Dict = {}
        self._load()

    @classmethod
    def instance(cls) -> "HitboxRepository":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    # -- loading -----------------------------------------------------------

    def _load(self):
        if self._loaded:
            return
        self._loaded = True

        if not self._yaml_path.exists():
            log_once(log, ("hitbox_yaml_missing", str(self._yaml_path)),
                     logging.WARNING,
                     "Hitbox data not found at %s; repository is empty "
                     "(no fabricated boxes).", self._yaml_path)
            return

        with open(self._yaml_path, "r") as f:
            raw = yaml.safe_load(f) or {}

        self._meta = raw.get("meta", {})
        self._base_hurtbox = [SourcedBox(**b) for b in raw.get("base_hurtbox", [])]
        if raw.get("pushbox"):
            self._pushbox = SourcedBox(**raw["pushbox"])
        if raw.get("throwbox"):
            self._throwbox = SourcedBox(**raw["throwbox"])

        for rom_id, rec in (raw.get("moves") or {}).items():
            self._moves[rom_id] = MoveRecord(**rec)

    # -- queries -----------------------------------------------------------

    def vitality(self) -> Optional[int]:
        """Life-bar scale of the ROM combat capture (0xA0 = 160), or None when
        the repository carries only the community tier (1050 scale)."""
        rc = (self._meta or {}).get("rom_combat") or {}
        v = rc.get("vitality")
        return int(v) if v else None

    def community_scale(self) -> float:
        """Factor mapping community-tier damage onto the scale the engine runs
        at: 1.0 without a capture; with one, 1/community_damage_scale, which
        recovers the raw (== ROM applied) value the capture confirmed
        (community 150 -> ROM 20 on the 160 life bar). Captured moves use their
        exact ROM value directly; this only rescales uncaptured moves."""
        rc = (self._meta or {}).get("rom_combat") or {}
        if not rc.get("vitality"):
            return 1.0
        scale = rc.get("community_damage_scale")
        return (1.0 / scale) if scale else (rc["vitality"] / 1050.0)

    def get_move_by_state(self, state_name: str,
                          variant: Optional[str] = None) -> Optional[MoveRecord]:
        """The move for a state, preferring `variant` (light/medium/heavy/
        air_*). Falls back to the state's un-varianted record, then to the
        lightest variant, so callers that don't know the strength still get
        a representative move."""
        candidates = [m for m in self._moves.values() if m.state == state_name]
        if candidates:
            if variant:
                for m in candidates:
                    if m.variant == variant:
                        return m
            for m in candidates:
                if m.variant is None:
                    return m
            candidates.sort(key=lambda m: (_VARIANT_ORDER.index(m.variant)
                                           if m.variant in _VARIANT_ORDER else 99))
            return candidates[0]
        # Most states (STANDING, JUMPING, walking, ...) legitimately have no ROM
        # attack move; this is the common, expected path. Keep it at debug so it
        # doesn't flood the console every frame.
        log_once(log, ("no_move_for_state", state_name), logging.DEBUG,
                 "No ROM move mapped to state %s; returning None.", state_name)
        return None

    def get_attack_boxes(self, state_name: str, frame_1indexed: int,
                         variant: Optional[str] = None) -> List[SourcedBox]:
        move = self.get_move_by_state(state_name, variant)
        if not move:
            return []
        return move.attack_boxes_for_frame(frame_1indexed)

    def get_vulnerability_boxes(self, state_name: str, frame_1indexed: int,
                                variant: Optional[str] = None) -> List[SourcedBox]:
        """Per-move vulnerability hurtbox extensions for a move's frame (or [])."""
        move = self.get_move_by_state(state_name, variant)
        if not move:
            return []
        return move.vulnerability_boxes_for_frame(frame_1indexed)

    def get_base_hurtboxes(self) -> List[SourcedBox]:
        return list(self._base_hurtbox)

    def get_pushbox(self) -> Optional[SourcedBox]:
        return self._pushbox

    def get_throwbox(self) -> Optional[SourcedBox]:
        return self._throwbox

    def get_crouch_hurtboxes(self) -> List[SourcedBox]:
        """Crouch hurtboxes, derived from the verified standing base boxes.

        We scale the ROM base-hurtbox heights toward the crouch bounding box
        from ``character_dimensions`` (~0.6 of standing). Geometry origin is the
        ROM idle data, so the boxes stay tagged ``verified`` / ``rom_id=idle``.
        """
        base = self.get_base_hurtboxes()
        if not base:
            # Fall back to the documented crouch bounding box as a single box.
            ox, oy, w, h = get_default_hurtbox_for_character("akuma", is_crouching=True)
            return [SourcedBox(offset_x=ox, offset_y=oy, width=w, height=h,
                               status="verified", rom_id="idle")]

        # Bounding crouch height from character_dimensions (negative = up).
        _, crouch_oy, _, crouch_h = get_default_hurtbox_for_character("akuma", is_crouching=True)
        standing_top = min(b.offset_y for b in base)  # most-negative top edge
        standing_h = -standing_top  # height of standing stack from feet
        scale = (crouch_h / standing_h) if standing_h else 0.6

        out: List[SourcedBox] = []
        for b in base:
            new_h = max(1.0, b.height * scale)
            # Keep boxes anchored at their bottom edge (feet side) then squash.
            bottom = b.offset_y + b.height  # bottom edge (closer to ground)
            new_top = bottom - new_h
            out.append(SourcedBox(offset_x=b.offset_x, offset_y=new_top,
                                  width=b.width, height=new_h,
                                  status="verified", rom_id="idle"))
        return out

    def iter_moves(self) -> Iterable[MoveRecord]:
        return list(self._moves.values())

    # -- reporting ---------------------------------------------------------

    def pending_report(self) -> str:
        """Human-readable summary of inferred / low-confidence / community items."""
        lines = ["Hitbox provenance report:"]
        lines.append(f"  moves loaded: {len(self._moves)}")
        named = [m for m in self._moves.values() if m.name_status == "metadata"]
        lines.append(f"  authoritative move names (framedata_meta.lua): {len(named)}")
        baston = [m for m in self._moves.values() if m.name_status == "baston"]
        lines.append(f"  authoritative move names (Baston cross-match): {len(baston)}")
        inferred = [m for m in self._moves.values() if m.name_status == "inferred"]
        lines.append(f"  inferred move names: {len(inferred)}")
        for m in inferred:
            conf = m.confidence or "?"
            tier = " (LOW CONFIDENCE)" if conf == "low" else ""
            combat = "community combat" if m.combat else "no combat"
            lines.append(f"    {m.rom_id} -> {m.state} [{conf}]{tier}, {combat}")
        unmapped = [m for m in self._moves.values() if not m.state]
        lines.append(f"  unmapped (geometry-only) moves: {len(unmapped)}")
        return "\n".join(lines)
