"""
ROM-accurate hitbox repository with enforced data provenance.

NO INVENTED DATA. This module is the single source of truth for Akuma's box
geometry. It loads `data/characters/akuma/hitboxes.yaml` (generated by
`tools/framedata/convert_3rd_training.py`) and refuses to load any box that is
not tagged with a provenance status. Three tiers exist:

  - verified : box geometry + frame timing, dumped from the SF3:3S ROM.
  - inferred : the ROM-pointer -> CharacterState (move name) assignment.
  - community: damage / stun / frame advantage (Baston ESN3S + tuning).

THE INVARIANT (enforced by Pydantic below): a `verified` box/source with no
provenance (empty repo or rom_id) fails to load. On a missing yaml or missing
entry the repository logs once and returns empty -- it NEVER fabricates boxes.
"""

from pathlib import Path
from typing import Dict, Iterable, List, Optional

import logging
import yaml
from pydantic import BaseModel, Field, model_validator

from street_fighter_3rd.data.character_dimensions import get_default_hurtbox_for_character
from street_fighter_3rd.util.logging_config import get_logger, log_once

log = get_logger(__name__)

# Resolve relative to repo root: src/street_fighter_3rd/data/<file> -> repo root.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_HITBOX_YAML = _REPO_ROOT / "data" / "characters" / "akuma" / "hitboxes.yaml"

_VALID_STATUSES = {"verified", "inferred", "community", "pending"}


class Provenance(BaseModel):
    """Where a box / move came from. ``verified`` requires real provenance."""

    status: str
    repo: str = ""
    commit: str = ""
    rom_id: str = ""
    source: str = ""

    @model_validator(mode="after")
    def _check_verified_has_provenance(self):
        if self.status not in _VALID_STATUSES:
            raise ValueError(f"unknown provenance status: {self.status!r}")
        if self.status == "verified":
            if not self.repo or not self.rom_id:
                raise ValueError(
                    "verified provenance requires non-empty repo and rom_id "
                    f"(got repo={self.repo!r}, rom_id={self.rom_id!r})"
                )
        return self


class SourcedBox(BaseModel):
    """A box that cannot exist without a provenance status."""

    offset_x: float
    offset_y: float
    width: float = Field(gt=0)
    height: float = Field(gt=0)
    status: str
    rom_id: str = ""

    @model_validator(mode="after")
    def _require_status(self):
        if not self.status:
            raise ValueError("SourcedBox requires a non-empty provenance status")
        if self.status not in _VALID_STATUSES:
            raise ValueError(f"unknown box status: {self.status!r}")
        return self


class CombatData(BaseModel):
    """Community-tier gameplay values (damage/stun/advantage)."""

    damage: int = 0
    stun: int = 0
    on_hit: int = 0
    on_block: int = 0
    hitstun: int = 0
    blockstun: int = 0
    hit_type: str = "MID"
    hit_effect: str = "NORMAL"
    status: str = "community"
    source: str = ""


class MoveRecord(BaseModel):
    """One ROM move entry plus optional inferred name + community combat."""

    rom_id: str
    timing: Dict[str, int]
    source: Provenance
    frames: List[Dict] = Field(default_factory=list)
    state: Optional[str] = None
    name_status: Optional[str] = None
    confidence: Optional[str] = None
    combat: Optional[CombatData] = None

    def attack_boxes_for_frame(self, frame_1indexed: int) -> List[SourcedBox]:
        boxes: List[SourcedBox] = []
        for fr in self.frames:
            if fr.get("frame") == frame_1indexed:
                for raw in fr.get("attack", []):
                    boxes.append(SourcedBox(**raw))
        return boxes

    def active_frames(self) -> List[int]:
        return [fr["frame"] for fr in self.frames if fr.get("attack")]


class HitboxRepository:
    """Lazy singleton loader for the ROM-verified hitbox YAML."""

    _instance: Optional["HitboxRepository"] = None

    def __init__(self, yaml_path: Optional[Path] = None):
        self._yaml_path = Path(yaml_path) if yaml_path else _HITBOX_YAML
        self._loaded = False
        self._base_hurtbox: List[SourcedBox] = []
        self._pushbox: Optional[SourcedBox] = None
        self._throwbox: Optional[SourcedBox] = None
        self._moves: Dict[str, MoveRecord] = {}
        self._meta: Dict = {}
        self._load()

    @classmethod
    def instance(cls) -> "HitboxRepository":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    # -- loading -----------------------------------------------------------

    def _load(self):
        if self._loaded:
            return
        self._loaded = True

        if not self._yaml_path.exists():
            log_once(log, ("hitbox_yaml_missing", str(self._yaml_path)),
                     logging.WARNING,
                     "Hitbox data not found at %s; repository is empty "
                     "(no fabricated boxes).", self._yaml_path)
            return

        with open(self._yaml_path, "r") as f:
            raw = yaml.safe_load(f) or {}

        self._meta = raw.get("meta", {})
        self._base_hurtbox = [SourcedBox(**b) for b in raw.get("base_hurtbox", [])]
        if raw.get("pushbox"):
            self._pushbox = SourcedBox(**raw["pushbox"])
        if raw.get("throwbox"):
            self._throwbox = SourcedBox(**raw["throwbox"])

        for rom_id, rec in (raw.get("moves") or {}).items():
            self._moves[rom_id] = MoveRecord(**rec)

    # -- queries -----------------------------------------------------------

    def get_move_by_state(self, state_name: str) -> Optional[MoveRecord]:
        for move in self._moves.values():
            if move.state == state_name:
                return move
        log_once(log, ("no_move_for_state", state_name), logging.INFO,
                 "No ROM move mapped to state %s; returning None.", state_name)
        return None

    def get_attack_boxes(self, state_name: str, frame_1indexed: int) -> List[SourcedBox]:
        move = self.get_move_by_state(state_name)
        if not move:
            return []
        return move.attack_boxes_for_frame(frame_1indexed)

    def get_base_hurtboxes(self) -> List[SourcedBox]:
        return list(self._base_hurtbox)

    def get_pushbox(self) -> Optional[SourcedBox]:
        return self._pushbox

    def get_throwbox(self) -> Optional[SourcedBox]:
        return self._throwbox

    def get_crouch_hurtboxes(self) -> List[SourcedBox]:
        """Crouch hurtboxes, derived from the verified standing base boxes.

        We scale the ROM base-hurtbox heights toward the crouch bounding box
        from ``character_dimensions`` (~0.6 of standing). Geometry origin is the
        ROM idle data, so the boxes stay tagged ``verified`` / ``rom_id=idle``.
        """
        base = self.get_base_hurtboxes()
        if not base:
            # Fall back to the documented crouch bounding box as a single box.
            ox, oy, w, h = get_default_hurtbox_for_character("akuma", is_crouching=True)
            return [SourcedBox(offset_x=ox, offset_y=oy, width=w, height=h,
                               status="verified", rom_id="idle")]

        # Bounding crouch height from character_dimensions (negative = up).
        _, crouch_oy, _, crouch_h = get_default_hurtbox_for_character("akuma", is_crouching=True)
        standing_top = min(b.offset_y for b in base)  # most-negative top edge
        standing_h = -standing_top  # height of standing stack from feet
        scale = (crouch_h / standing_h) if standing_h else 0.6

        out: List[SourcedBox] = []
        for b in base:
            new_h = max(1.0, b.height * scale)
            # Keep boxes anchored at their bottom edge (feet side) then squash.
            bottom = b.offset_y + b.height  # bottom edge (closer to ground)
            new_top = bottom - new_h
            out.append(SourcedBox(offset_x=b.offset_x, offset_y=new_top,
                                  width=b.width, height=new_h,
                                  status="verified", rom_id="idle"))
        return out

    def iter_moves(self) -> Iterable[MoveRecord]:
        return list(self._moves.values())

    # -- reporting ---------------------------------------------------------

    def pending_report(self) -> str:
        """Human-readable summary of inferred / low-confidence / community items."""
        lines = ["Hitbox provenance report:"]
        lines.append(f"  moves loaded: {len(self._moves)}")
        named = [m for m in self._moves.values() if m.name_status == "metadata"]
        lines.append(f"  authoritative move names (framedata_meta.lua): {len(named)}")
        baston = [m for m in self._moves.values() if m.name_status == "baston"]
        lines.append(f"  authoritative move names (Baston cross-match): {len(baston)}")
        inferred = [m for m in self._moves.values() if m.name_status == "inferred"]
        lines.append(f"  inferred move names: {len(inferred)}")
        for m in inferred:
            conf = m.confidence or "?"
            tier = " (LOW CONFIDENCE)" if conf == "low" else ""
            combat = "community combat" if m.combat else "no combat"
            lines.append(f"    {m.rom_id} -> {m.state} [{conf}]{tier}, {combat}")
        unmapped = [m for m in self._moves.values() if not m.state]
        lines.append(f"  unmapped (geometry-only) moves: {len(unmapped)}")
        return "\n".join(lines)
